<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "sf_event_mgt"
 *
 * Auto generated by Extension Builder 2014-05-17
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Event management and registration',
    'description' => 'Configurable event management and registration extension based on ExtBase and Fluid',
    'category' => 'plugin',
    'author' => 'Torben Hansen',
    'author_email' => 'derhansen@gmail.com',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 1,
    'version' => '1.8.1',
    'constraints' => [
        'depends' => [
            'extbase' => '6.2.0',
            'fluid' => '6.2.0',
            'typo3' => '6.2.0-7.6.99',
            'php' => '5.4.0-7.0.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
