<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "sf_event_mgt"
 *
 * Auto generated by Extension Builder 2014-05-17
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Event management and booking',
	'description' => 'Event management with booking option',
	'category' => 'plugin',
	'author' => 'Torben Hansen',
	'author_email' => 'derhansen@gmail.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.2',
			'fluid' => '6.2',
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);