<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "sf_event_mgt"
 *
 * Auto generated by Extension Builder 2014-05-17
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Event management and registration',
	'description' => 'Configurable event management and registration extension based on ExtBase and Fluid',
	'category' => 'plugin',
	'author' => 'Torben Hansen',
	'author_email' => 'derhansen@gmail.com',
	'author_company' => 'Skyfillers GmbH',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0-dev',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.2.0',
			'fluid' => '6.2.0',
			'typo3' => '6.2.0-6.2.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
