services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  DERHANSEN\SfEventMgt\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  DERHANSEN\SfEventMgt\Service\RegistrationService:
    public: true